name: Check Build

on:
  push:
    branches: [zl]
  pull_request:
    branches: [zl]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_doc:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependency
        shell: bash
        run: |
          sudo apt-get install -y pandoc jq
          pip install sphinx pydata-sphinx-theme pandoc \
            nbsphinx sphinx-autodoc-typehints myst-parser myst_nb \
            sphinx_copybutton sphinxcontrib.bibtex sphinx_tabs
      - name: Build doc
        shell: bash
        run: sphinx-build ${GITHUB_WORKSPACE}/docs _build/html
      - name: Deploy doc
        uses: JamesIves/github-pages-deploy-action@v4
  build_package:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "**/pyproject.toml"
      - name: Install build dependencies
        run: python -m pip install --upgrade pip wheel twine build
      - name: Build package
        run: python -m build
      - name: Check package
        run: twine check --strict dist/*.whl
